baseURL = "https://brunomaletta.github.io/Biblioteca" # (or set via env variable HUGO_BASEURL)
languageCode = "pt-BR"
title = "Biblioteca"
contentDir = "content"
enableEmoji = true

defaultContentLanguage = 'pt'
[languages]
  [languages.pt]
    title = "Biblioteca Maratona UFMG"
    languageName = "Português"
    weight = 10
  # [languages.fr]
  #   title = "Lotus Docs Exemple de Site"
  #   languageName = "Français"
  #   contentDir = "content/fr"
  #   weight = 20

[module]
  [module.hugoVersion]
    extended = true
    min = "0.100.0"
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  # [markup.highlight]
  #   codeFences = false # disables Hugo's default syntax highlighting
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true

[params]

  # Google Fonts
  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font = "Inter"     # Default is System font
  secondary_font  = "Inter"     # Default is System font
  mono_font       = "Fira Code" # Default is System font

    [params.footer]
        copyright = "© :YEAR:. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
        version   = true # include git commit info in footer

    [params.social]
        github = "brunomaletta/Biblioteca" # github.com/YOUR_GITHUB_ID
        # twitter = ""            # twitter.com/YOUR_TWITTER_ID
        # instagram = ""      # instagram.com/YOUR_INSTAGRAM_ID
        # rss = true                     # show rss icon with link

    [params.docs] # Parameters for the /docs 'template'
        title           = "Docs"                        # default html title for documentation pages/sections

        # pathName        = "docs"                            # path for documentation site | default "docs"

        themeColor      = "red"                            # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan

        darkMode        = true                                # enable dark mode option? default false

        prism           = true                                # enable syntax highlighting via Prism

        prismTheme      = "lotusdocs"                         # (optional) - Set theme for PrismJS. Options include: lotusdocs (default), solarized-light, twilight, lucario

#         # gitinfo
        repoURL         = "https://github.com/brunomaletta/Biblioteca"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
        repoBranch      = "release"                           # Name of your Git repository branch
        editPage        = true                                # enable 'Edit this page' feature - default false
        lastMod         = true                                # enable 'Last modified' date on pages - default false
        lastModRelative = true                                # format 'Last modified' time as relative - default true

        # ToC
        toc             = true                                # enable table of contents? default is true
        tocMobile       = true                                # enable table of contents in mobile view? default is true
        scrollSpy       = true                                # enable scrollspy on ToC? default is true

        # icons
        sidebarIcons    = true                                # enable sidebar icons? default false
        titleIcon       = true                                # enable front matter icon title prefix? default is false

        # content navigation
        breadcrumbs     = true                                # default is true
        navDesc         = true                                # include front matter descriptions in Prev/Next navigation cards
        navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

        listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description
        backToTop       = true                                # enable back-to-top button? default true

        # front matter
        descriptions    = true                                # enable front matter descriptions under content title?

        # Link behaviour
        intLinkTooltip  = true                                # Enable a tooltip for internal links that displays info about the destination? default false
        extLinkNewTab   = true                               # Open external links in a new Tab? default true
        # logoLinkURL = ""                                      # Set a custom URL destination for the top header logo link.

    [params.flexsearch] # Parameters for FlexSearch
        enabled             = true
        # tokenize            = "full"
        # optimize            = true
        # cache               = 100
        # minQueryChar        = 3 # default is 0 (disabled)
        # maxResult           = 5 # default is 5
        # searchSectionsIndex = []

    [params.feedback]
        enabled = false
#         emoticonTpl = true
#         eventDest = ["plausible","google"]
#         emoticonEventName = "Feedback"
#         positiveEventName = "Positive Feedback"
#         negativeEventName = "Negative Feedback"
#         positiveFormTitle = "What did you like?"
#         negativeFormTitle = "What went wrong?"
#         successMsg = "Thank you for helping to improve Lotus Docs' documentation!"
#         errorMsg = "Sorry! There was an error while attempting to submit your feedback!"
#         positiveForm = [
#           ["Accurate", "Accurately describes the feature or option."],
#           ["Solved my problem", "Helped me resolve an issue."],
#           ["Easy to understand", "Easy to follow and comprehend."],
#           ["Something else"]
#         ]
#         negativeForm = [
#           ["Inaccurate", "Doesn't accurately describe the feature or option."],
#           ["Couldn't find what I was looking for", "Missing important information."],
#           ["Hard to understand", "Too complicated or unclear."],
#           ["Code sample errors", "One or more code samples are incorrect."],
#           ["Something else"]
#         ]

[[menu.primary]]
    name  = "Docs"
    url =  "/docs/"
    identifier = "docs"
    weight = 10

# # [[menu.primary]]
# #     name  = "Showcase"
# #     url = "/showcase"
# #     identifier = "showcase"
# #     weight = 20

# [[menu.primary]]
#     name  = "Community"
#     url = "https://github.com/colinwilson/lotusdocs/discussions"
#     identifier = "community"
#     weight = 30


