CXX = g++
CXXFLAGS = -fsanitize=address -O1 -fno-omit-frame-pointer -g -Wall -Wshadow -std=c++14 -Wno-unused-result -Wno-sign-compare

CXXFLAGS = -fsanitize=address,undefined -fno-sanitize-recover=all -D_GLIBCXX_DEBUG -O1 -fno-omit-frame-pointer -g -Wall -Wshadow -Wconversion -std=c++14 -Wno-unused-result -Wno-sign-compare
